language: python

python: "2.7"

sudo: false

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
- py.test -vv --cov=sheepdog --cov-report xml tests

after_script:
- python-codacy-coverage -r coverage.xml
